services:
  audiobookbay-downloader:
    image: ghcr.io/zprough/audiobookbay-automated:1.0.3
    container_name: audiobookbay-downloader
    restart: unless-stopped
    network_mode: service:warp
    depends_on:
      - warp
    volumes:
      - $DOCKERDIR/appdata/audiobookbay-automated:/config
      - $DATADIR/Audiobooks:/audiobooks
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_SCHEME=http
      - DL_HOST=rdtclient
      - DL_PORT=6500
      - DL_USERNAME=/run/secrets/rdtclient_username
      - DL_PASSWORD=/run/secrets/rdtclient_password
      - DL_CATEGORY=abb-downloader
      - SAVE_PATH_BASE=/audiobooks
      - ABB_HOSTNAME=audiobookbay.lu
      - INCOGNITO_MODE=true
      - ROTATE_USER_AGENT=true
      - DISABLE_CACHE_BUST=false
      - ABB_TIMEOUT=8
      # - NAV_LINK_NAME=Open Audiobook Player
      # - NAV_LINK_URL=https://audiobooks.yourdomain.com/
    secrets:
      - rdtclient_password
      - rdtclient_username
    labels:
      homepage.group: Media-Management
      homepage.name: audiobookbay-automated
      homepage.icon: /icons/audiobookbay.png
      homepage.href: http://${SERVER_LAN_IP}:5078