version: '3.8'

services:
  audiobookbay-automated:
    # Use a specific version for production deployments
    # image: ghcr.io/zprough/audiobookbay-automated:v1.0.0
    # Or use latest for development
    image: ghcr.io/zprough/audiobookbay-automated:latest
    ports:
      - "5078:5078"
    container_name: audiobookbay-automated
    environment:
      - DOWNLOAD_CLIENT=${DOWNLOAD_CLIENT}
      - DL_HOST=${DL_HOST}
      - DL_PORT=${DL_PORT}
      - DL_USERNAME=${DL_USERNAME}
      - DL_PASSWORD=${DL_PASSWORD}
      - DL_CATEGORY=${DL_CATEGORY}
      - SAVE_PATH_BASE=${SAVE_PATH_BASE}
      - NAV_LINK_NAME=${NAV_LINK_NAME}
      - NAV_LINK_URL=${NAV_LINK_URL}
    env_file:
      - .env