services:
  audiobookbay-downloader:
    image: ghcr.io/zprough/audiobookbay-automated:latest
    container_name: audiobookbay-downloader
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "5078:5078"
    volumes:
      - $DOCKERDIR/appdata/audiobookbay-automated:/config
      - $DATADIR/Audiobooks:/audiobooks
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_SCHEME=http
      - DL_HOST=rdtclient
      - DL_PORT=6500
      - DL_USERNAME=/run/secrets/rdtclient_username
      - DL_PASSWORD=/run/secrets/rdtclient_password
      - DL_CATEGORY=abb-downloader
      - SAVE_PATH_BASE=/audiobooks
      - ABB_HOSTNAME=audiobookbay.lu
      # - ABB_HOSTNAME='audiobookbay.is' #Default
      # - NAV_LINK_NAME=Open Audiobook Player #Optional
      # - NAV_LINK_URL=https://audiobooks.yourdomain.com/ #Optional
    secrets:
      - rdtclient_password
      - rdtclient_username
    labels:
      # Homepage Dashboard
      homepage.group: Media-Management
      homepage.name: audiobookbay-automated
      homepage.icon: /icons/audiobookbay.png
      homepage.href: http://${SERVER_LAN_IP}:5078